# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ios-shoppe-demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios-shoppe-demo

  target 'ios-shoppe-demoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ios-shoppe-demoUITests' do
    # Pods for testing
  end

end
