# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ios-shoppe-demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios-shoppe-demo
  # Project currently using SwiftPackageManager, but this was left as an example
  # pod 'FullStory', :http => 'https://ios-releases.fullstory.com/fullstory-1.19.1.tar.gz'

  target 'ios-shoppe-demoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ios-shoppe-demoUITests' do
    # Pods for testing
  end

end
