# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ios-shoppe-demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios-shoppe-demo
pod 'FullStory', :http => 'https://ios-releases.fullstory.com/fullstory-1.4.0.tar.gz'
pod 'Analytics', '~> 3.0'
pod 'FullStorySegmentMiddleware', :git => 'https://github.com/fullstorydev/fullstory-segment-middleware-ios.git', :branch => 'dev-preview-1'

  target 'ios-shoppe-demoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ios-shoppe-demoUITests' do
    # Pods for testing
  end

end
